{"path":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","commits":[{"id":"5350389bf83287111f7760b9e3db3af8e3648474","date":1216372812,"type":0,"author":"Michael McCandless","isMerge":false,"pathNew":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","pathOld":"/dev/null","sourceNew":"    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.TOKENIZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.TOKENIZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.UN_TOKENIZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.TOKENIZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.UN_TOKENIZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.UN_TOKENIZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.UN_TOKENIZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 3000;\n\n      while(System.currentTimeMillis() < stopTime) {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      }\n    }\n\n","sourceOld":null,"bugFix":null,"bugIntro":["a78a90fc9701e511308346ea29f4f5e548bb39fe","a6e0058e8d624d1fea85b51b1dba5d5623dc2eb7"],"isBuggy":true,"nexts":[],"revCommit":null},{"id":"b5015bd4c211c4f399ae66ee20fe6841ba5b0b6a","date":1221082732,"type":3,"author":"Michael McCandless","isMerge":false,"pathNew":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","pathOld":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","sourceNew":"    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 3000;\n\n      while(System.currentTimeMillis() < stopTime) {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      }\n    }\n\n","sourceOld":"    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.TOKENIZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.TOKENIZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.UN_TOKENIZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.TOKENIZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.UN_TOKENIZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.UN_TOKENIZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.UN_TOKENIZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 3000;\n\n      while(System.currentTimeMillis() < stopTime) {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      }\n    }\n\n","bugFix":null,"bugIntro":[],"isBuggy":true,"nexts":[],"revCommit":null},{"id":"1326054a8d3aa66382d49decc7f330955c9c6f71","date":1257386139,"type":3,"author":"Uwe Schindler","isMerge":false,"pathNew":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","pathOld":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","sourceNew":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 3000;\n\n      while(System.currentTimeMillis() < stopTime) {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      }\n    }\n\n","sourceOld":"    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 3000;\n\n      while(System.currentTimeMillis() < stopTime) {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      }\n    }\n\n","bugFix":null,"bugIntro":[],"isBuggy":true,"nexts":[],"revCommit":null},{"id":"90cb6b3f4e5652555b614adc90204287fbebd27c","date":1259494272,"type":3,"author":"Michael McCandless","isMerge":false,"pathNew":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","pathOld":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","sourceNew":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 500;\n\n      while(System.currentTimeMillis() < stopTime) {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      }\n    }\n\n","sourceOld":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 3000;\n\n      while(System.currentTimeMillis() < stopTime) {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      }\n    }\n\n","bugFix":null,"bugIntro":[],"isBuggy":true,"nexts":[],"revCommit":null},{"id":"a6e0058e8d624d1fea85b51b1dba5d5623dc2eb7","date":1261132949,"type":3,"author":"Uwe Schindler","isMerge":false,"pathNew":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","pathOld":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","sourceNew":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 500;\n\n      do {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      } while(System.currentTimeMillis() < stopTime);\n    }\n\n","sourceOld":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 500;\n\n      while(System.currentTimeMillis() < stopTime) {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      }\n    }\n\n","bugFix":["5350389bf83287111f7760b9e3db3af8e3648474"],"bugIntro":[],"isBuggy":true,"nexts":[],"revCommit":null},{"id":"42607aa380c892dc1ec0ab26e86a575c28e13618","date":1268641604,"type":3,"author":"Uwe Schindler","isMerge":false,"pathNew":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","pathOld":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","sourceNew":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 500;\n\n      do {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (VERBOSE) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      } while(System.currentTimeMillis() < stopTime);\n    }\n\n","sourceOld":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 500;\n\n      do {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (DEBUG) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      } while(System.currentTimeMillis() < stopTime);\n    }\n\n","bugFix":null,"bugIntro":[],"isBuggy":true,"nexts":[],"revCommit":null},{"id":"9454a6510e2db155fb01faa5c049b06ece95fab9","date":1453508333,"type":5,"author":"Dawid Weiss","isMerge":false,"pathNew":"lucene/src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","pathOld":"src/test/org/apache/lucene/index/TestIndexWriterExceptions.IndexerThread#run().mjava","sourceNew":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 500;\n\n      do {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (VERBOSE) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      } while(System.currentTimeMillis() < stopTime);\n    }\n\n","sourceOld":"    @Override\n    public void run() {\n\n      final Document doc = new Document();\n\n      doc.add(new Field(\"content1\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.ANALYZED));\n      doc.add(new Field(\"content6\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n      doc.add(new Field(\"content2\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NOT_ANALYZED));\n      doc.add(new Field(\"content3\", \"aaa bbb ccc ddd\", Field.Store.YES, Field.Index.NO));\n\n      doc.add(new Field(\"content4\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.ANALYZED));\n      doc.add(new Field(\"content5\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED));\n\n      doc.add(new Field(\"content7\", \"aaa bbb ccc ddd\", Field.Store.NO, Field.Index.NOT_ANALYZED, Field.TermVector.WITH_POSITIONS_OFFSETS));\n\n      final Field idField = new Field(\"id\", \"\", Field.Store.YES, Field.Index.NOT_ANALYZED);\n      doc.add(idField);\n\n      final long stopTime = System.currentTimeMillis() + 500;\n\n      do {\n        doFail.set(this);\n        final String id = \"\"+r.nextInt(50);\n        idField.setValue(id);\n        Term idTerm = new Term(\"id\", id);\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (RuntimeException re) {\n          if (VERBOSE) {\n            System.out.println(\"EXC: \");\n            re.printStackTrace(System.out);\n          }\n          try {\n            _TestUtil.checkIndex(writer.getDirectory());\n          } catch (IOException ioe) {\n            System.out.println(Thread.currentThread().getName() + \": unexpected exception1\");\n            ioe.printStackTrace(System.out);\n            failure = ioe;\n            break;\n          }\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception2\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n\n        doFail.set(null);\n\n        // After a possible exception (above) I should be able\n        // to add a new document without hitting an\n        // exception:\n        try {\n          writer.updateDocument(idTerm, doc);\n        } catch (Throwable t) {\n          System.out.println(Thread.currentThread().getName() + \": unexpected exception3\");\n          t.printStackTrace(System.out);\n          failure = t;\n          break;\n        }\n      } while(System.currentTimeMillis() < stopTime);\n    }\n\n","bugFix":null,"bugIntro":[],"isBuggy":true,"nexts":[],"revCommit":null}],"commit2Parents":{"1326054a8d3aa66382d49decc7f330955c9c6f71":["b5015bd4c211c4f399ae66ee20fe6841ba5b0b6a"],"90cb6b3f4e5652555b614adc90204287fbebd27c":["1326054a8d3aa66382d49decc7f330955c9c6f71"],"a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85":[],"b5015bd4c211c4f399ae66ee20fe6841ba5b0b6a":["5350389bf83287111f7760b9e3db3af8e3648474"],"42607aa380c892dc1ec0ab26e86a575c28e13618":["a6e0058e8d624d1fea85b51b1dba5d5623dc2eb7"],"5350389bf83287111f7760b9e3db3af8e3648474":["a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85"],"cd5edd1f2b162a5cfa08efd17851a07373a96817":["9454a6510e2db155fb01faa5c049b06ece95fab9"],"9454a6510e2db155fb01faa5c049b06ece95fab9":["42607aa380c892dc1ec0ab26e86a575c28e13618"],"a6e0058e8d624d1fea85b51b1dba5d5623dc2eb7":["90cb6b3f4e5652555b614adc90204287fbebd27c"]},"commit2Childs":{"1326054a8d3aa66382d49decc7f330955c9c6f71":["90cb6b3f4e5652555b614adc90204287fbebd27c"],"90cb6b3f4e5652555b614adc90204287fbebd27c":["a6e0058e8d624d1fea85b51b1dba5d5623dc2eb7"],"a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85":["5350389bf83287111f7760b9e3db3af8e3648474"],"b5015bd4c211c4f399ae66ee20fe6841ba5b0b6a":["1326054a8d3aa66382d49decc7f330955c9c6f71"],"42607aa380c892dc1ec0ab26e86a575c28e13618":["9454a6510e2db155fb01faa5c049b06ece95fab9"],"5350389bf83287111f7760b9e3db3af8e3648474":["b5015bd4c211c4f399ae66ee20fe6841ba5b0b6a"],"a6e0058e8d624d1fea85b51b1dba5d5623dc2eb7":["42607aa380c892dc1ec0ab26e86a575c28e13618"],"cd5edd1f2b162a5cfa08efd17851a07373a96817":[],"9454a6510e2db155fb01faa5c049b06ece95fab9":["cd5edd1f2b162a5cfa08efd17851a07373a96817"]},"heads":["cd5edd1f2b162a5cfa08efd17851a07373a96817"],"roots":["a0e7ee9d0d12370e8d2b5ae0a23b6e687e018d85"],"pathCommit":null}